const data = [
  {
    id: 1,
    name: "MOCK - iPhone 12",
    brand: "Apple",
    category: "gama-alta",
    image: "../images/apple/IPHONE_12.png",
    price: 803760,
    stock: 18,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 2,
    name: "MOCK - V20",
    brand: "Vivo",
    category: "gama-media",
    image: "../images/vivo/VIVO_V20.png",
    price: 431760,
    stock: 25,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 3,
    name: "MOCK - Mi 10T Pro",
    brand: "Xiaomi",
    category: "gama-alta",
    image: "../images/xiaomi/XIAOMI_MI_10T_PRO.png",
    price: 635760,
    stock: 50,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 4,
    name: "MOCK - Galaxy S20",
    brand: "Samsung",
    category: "gama-alta",
    image: "../images/samsung/GALAXY_S20.png",
    price: 647760,
    stock: 27,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 5,
    name: "MOCK - Redmi Note 9",
    brand: "Xiaomi",
    category: "gama-media",
    image: "../images/xiaomi/REDMI_NOTE_9.png",
    price: 227760,
    stock: 28,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 6,
    name: "MOCK - Nokia 2.3",
    brand: "Nokia",
    category: "gama-baja",
    image: "../images/nokia/NOKIA_2-3.png",
    price: 119760,
    stock: 5,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 7,
    name: "MOCK - iPhone SE",
    brand: "Apple",
    category: "gama-media",
    image: "../images/apple/IPHONE_SE.png",
    price: 227760,
    stock: 5,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 8,
    name: "MOCK - Y11s",
    brand: "Vivo",
    category: "gama-baja",
    image: "../images/vivo/VIVO_Y11S.png",
    price: 83760,
    stock: 43,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 9,
    name: "MOCK - Velvet",
    brand: "LG",
    category: "gama-alta",
    image: "../images/lg/LG_VELVET.png",
    price: 419760,
    stock: 49,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 10,
    name: "MOCK - Galaxy S21 Ultra",
    brand: "Samsung",
    category: "gama-alta",
    image: "../images/samsung/GALAXY_S21_ULTRA.png",
    price: 1199760,
    stock: 5,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 11,
    name: "MOCK - K41",
    brand: "LG",
    category: "gama-baja",
    image: "../images/lg/K41S.png",
    price: 167760,
    stock: 15,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
  {
    id: 12,
    name: "MOCK - Nokia 6.2",
    brand: "Nokia",
    category: "gama-baja",
    image: "../images/nokia/NOKIA_6-2.png",
    price: 131760,
    stock: 36,
    description: {
      screen: "Pantalla 6,1 OLED Súper Retina XDR",
      frontCamera: "Cámara frontal 12 MP",
      mainCamera: "Cámara trasera 12 MP  + 12 MP",
      processor: "ProcesadorApple A14 Bionic",
    },
  },
];

export default data;
